// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RestClientPropertyType = ("STRING" | "PASSWORD" | "PATH")
export type Severity = "INFO" | "WARNING" | "ERROR";

export interface Restclients {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  javaType: JavaType[];
  restClientContext: RestClientContext;
  restClientEditorData: RestClientEditorData;
  restClientSaveDataArgs: RestClientSaveDataArgs;
  restPropertyMeta: RestPropertyMeta[];
  validationResult: ValidationResult[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface JavaType {
  fullQualifiedName: string;
  packageName: string;
  simpleName: string;
}
export interface RestClientContext {
  app: string;
  file: string;
  pmv: string;
}
export interface RestClientEditorData {
  context: RestClientContext;
  data: RestClientData[];
  helpUrl: string;
  readonly: boolean;
}
export interface RestClientData {
  description: string;
  features: string[];
  icon: string;
  id: string;
  name: string;
  openApi: RestClientOpenApi;
  properties: RestClientProperty[];
  uri: string;
}
export interface RestClientOpenApi {
  namespace: string;
  resolveFully: boolean;
  spec: string;
}
export interface RestClientProperty {
  key: string;
  type: RestClientPropertyType;
  value: string;
}
export interface RestClientSaveDataArgs {
  context: RestClientContext;
  data: RestClientData[];
  directSave: boolean;
}
export interface RestPropertyMeta {
  description: string;
  property: string;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
