// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface RestClients {
  boolean: boolean;
  editorFileContent: EditorFileContent;
  roleMeta: RoleMeta[];
  restClientContext: RestClientContext;
  restClientEditorData: RestClientEditorData;
  restClientSaveDataArgs: RestClientSaveDataArgs;
  validationResult: ValidationResult[];
  [k: string]: unknown;
}
export interface EditorFileContent {
  content: string;
}
export interface RoleMeta {
  id: string;
  label: string;
}
export interface RestClientContext {
  app: string;
  file: string;
  pmv: string;
}
export interface RestClientEditorData {
  context: RestClientContext;
  data: RestClientData[];
  helpUrl: string;
  readonly: boolean;
}
export interface RestClientData {
  emailAddress: string;
  fullName: string;
  name: string;
  password: string;
  properties: MapStringString;
  roles: string[];
}
export interface MapStringString {
  [k: string]: string;
}
export interface RestClientSaveDataArgs {
  context: RestClientContext;
  data: RestClientData[];
  directSave: boolean;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
